/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState } from "react";
import { Upload, Cpu, Navigation, FileCheck, Check, ArrowRight, BrainCircuit, Sparkles, MapPin, Download } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { TimelineStep } from "../types";

export default function HowItWorks() {
  const [activeStep, setActiveStep] = useState<number>(1);

  const steps: TimelineStep[] = [
    {
      step: 1,
      title: "Upload Surplus Food",
      subtitle: "Kitchen Stock Capture",
      description: "Under 60 seconds, hotels or restaurants register excess fresh ingredients, bakery goods, buffet plates, or edible surplus on the PANTAS partner panel.",
      items: ["Camera quick-snap upload", "Automatic weight entry", "Pre-set category templates", "Allergy disclaimer indicators"],
      type: "upload"
    },
    {
      step: 2,
      title: "AI Intelligent Classification",
      subtitle: "Surplus Quality triage",
      description: "Our proprietary AI model evaluates safety markers, culinary lifetime, and outlet coordinates to divide the item into optimized circular path tiers.",
      items: ["Tier A: Edible meals for market sale", "Tier B: Immediate NGO donation", "Tier C: Feedstock for Maggot Farms", "Tier D: Compost/Soil nutrition Conversion"],
      type: "classification"
    },
    {
      step: 3,
      title: "Smart Grid Redistribution",
      subtitle: "Dynamic Logistics & Alerts",
      description: "PANTAS automatically updates consumer apps with flash-sale countdowns up to 70% off, pings active charity networks, or schedules local organic waste pickups.",
      items: ["Proximity-alert pings to buyers", "Instant eco-tax receipt generated", "Automated fleet routing", "Regional logistics integration"],
      type: "distribution"
    },
    {
      step: 4,
      title: "ESG Ledger Integration",
      subtitle: "Autogenerated CSR Disclosure",
      description: "Each successful diversion generates blockchain-logged emission mitigation and water saving values, formatted specifically for automated ESG disclosure reporting.",
      items: ["GRI Standards compliant data", "Direct board room presentation slides", "Third-party audited credits logs", "Downloadable impact reports"],
      type: "esg"
    }
  ];

  const currentStepData = steps.find((s) => s.step === activeStep) || steps[0];

  return (
    <section id="how-it-works" className="relative py-24 bg-[#090D16] overflow-hidden border-t border-b border-white/5">
      {/* Background radial highlights */}
      <div className="absolute top-1/4 left-1/3 w-[300px] h-[300px] bg-brand-primary/10 rounded-full blur-[80px] pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-[350px] h-[350px] bg-brand-emerald/10 rounded-full blur-[90px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Header Title */}
        <div className="max-w-3xl mx-auto text-center mb-16">
          <span className="text-xs font-mono tracking-widest text-brand-primary font-semibold bg-brand-primary/10 px-3.5 py-1 rounded-full uppercase">
            Platform Workflow
          </span>
          <h2 className="mt-4 text-3xl sm:text-4xl font-display font-extrabold text-white tracking-tight leading-tight">
            How PANTAS Orchestrates Surplus
          </h2>
          <p className="mt-4 text-[#94A3B8] text-base leading-relaxed">
            Our platform operates with lightweight steps, wrapping core complex artificial intelligence into human-friendly hotel kitchen and processor workflows.
          </p>
        </div>

        {/* 4-Step Horizontal Navigation bar */}
        <div className="relative mb-16">
          {/* Horizontal connecting line behind the steps */}
          <div className="absolute top-1/2 left-[12.5%] right-[12.5%] h-0.5 bg-white/5 -translate-y-1/2 hidden md:block" />
          
          {/* Active step progress indicator fill */}
          <div 
            className="absolute top-1/2 left-[12.5%] h-0.5 bg-gradient-to-r from-brand-primary to-brand-emerald -translate-y-1/2 hidden md:block transition-all duration-500 ease-out"
            style={{ width: `${((activeStep - 1) / 3) * 75}%` }}
          />

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 relative z-10">
            {steps.map((item) => {
              const completed = item.step < activeStep;
              const active = item.step === activeStep;
              return (
                <button
                  key={item.step}
                  onClick={() => setActiveStep(item.step)}
                  className="flex flex-col items-center text-center group"
                >
                  <div className={`w-12 h-12 rounded-full border-2 flex items-center justify-center transition-all duration-300 ${
                    active 
                      ? "bg-[#0B0F19] border-brand-primary text-brand-primary shadow-lg shadow-brand-primary/20 scale-110" 
                      : completed 
                        ? "bg-brand-primary border-brand-primary text-brand-navy" 
                        : "bg-[#090D16] border-white/10 text-white/40 group-hover:border-white/20"
                  }`}>
                    {completed ? (
                      <Check className="w-5 h-5 stroke-[2.5]" />
                    ) : (
                      <span className="font-mono text-xs font-bold">{item.step}</span>
                    )}
                  </div>

                  <span className={`block text-xs font-mono tracking-wide uppercase mt-4 transition-colors ${
                    active ? "text-brand-primary font-bold" : "text-[#64748B] group-hover:text-white"
                  }`}>
                    {item.subtitle}
                  </span>
                  <span className={`block text-sm font-semibold mt-1 transition-colors ${
                    active ? "text-white" : "text-white/60 group-hover:text-white"
                  }`}>
                    {item.title}
                  </span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Dynamic Display Details panel mimicking phone mockup */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center bg-[#0B0F19]/60 rounded-3xl border border-white/5 p-6 sm:p-10 backdrop-blur-xl">
          
          {/* Step description */}
          <div className="lg:col-span-5 space-y-6">
            <div>
              <span className="text-xs font-mono text-brand-primary uppercase tracking-widest bg-brand-primary/10 px-3 py-1 rounded-full w-fit">
                STEP 0{currentStepData.step} INFO
              </span>
              <h3 className="mt-4 text-2xl sm:text-3xl font-display font-extrabold text-white tracking-tight leading-tight">
                {currentStepData.title}
              </h3>
              <p className="mt-3 text-[#94A3B8] text-xs sm:text-sm leading-relaxed">
                {currentStepData.description}
              </p>
            </div>

            <div className="space-y-3 bg-white/[0.01] border border-white/5 rounded-xl p-4">
              <span className="block text-[10px] font-mono text-[#64748B] uppercase tracking-wider">
                CORE SYSTEM METRIC ALIGNED :
              </span>
              <div className="space-y-2">
                {currentStepData.items.map((bullet, i) => (
                  <div key={i} className="flex gap-2.5 items-center text-xs text-white/90 font-sans">
                    <div className="w-1.5 h-1.5 rounded-full bg-brand-primary" />
                    <span>{bullet}</span>
                  </div>
                ))}
              </div>
            </div>

            <button 
              onClick={() => setActiveStep((prev) => (prev < 4 ? prev + 1 : 1))}
              className="inline-flex items-center gap-1.5 text-xs font-mono text-brand-primary hover:text-white transition-colors uppercase group font-bold"
            >
              <span>{activeStep === 4 ? "Back to Step 1" : "Next Process Step"}</span>
              <ArrowRight className="w-3.5 h-3.5 transition-transform group-hover:translate-x-1" />
            </button>
          </div>

          {/* Interactive UI Mockups */}
          <div className="lg:col-span-7">
            <div className="relative rounded-2xl bg-[#090D16] border border-white/10 p-5 sm:p-6 overflow-hidden min-h-[300px] flex flex-col justify-between">
              
              <AnimatePresence mode="wait">
                {/* Step 1 Mockup: Upload Surplus */}
                {activeStep === 1 && (
                  <motion.div
                    key="step-1"
                    initial={{ opacity: 0, scale: 0.98 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    className="space-y-4 w-full"
                  >
                    <div className="flex justify-between items-center bg-white/[0.02] border border-white/5 p-3 rounded-xl">
                      <div className="flex items-center gap-2">
                        <Upload className="w-4 h-4 text-brand-primary animate-bounce" />
                        <span className="text-xs font-semibold text-white/95">Snapping Bakery Stock: Grand Premier Hotel</span>
                      </div>
                      <span className="font-mono text-[9px] text-[#22C55E] bg-brand-primary/10 px-2 py-0.5 rounded border border-brand-primary/20">
                        Camera Ready
                      </span>
                    </div>

                    <div className="relative border border-white/5 rounded-2xl aspect-video bg-[#070A11] flex items-center justify-center overflow-hidden">
                      {/* Grid Camera overlay */}
                      <div className="absolute inset-2 border border-white/5 border-dashed rounded-xl pointer-events-none" />
                      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-14 h-14 border border-brand-primary/30 rounded-full animate-ping pointer-events-none" />
                      
                      {/* Mockup food plate outline with premium overlay */}
                      <div className="text-center space-y-2 z-15">
                        <span className="block text-[11px] font-mono text-[#475569]">AI INSTANT EDGE OBJECT DETECTION</span>
                        <div className="px-4 py-2 bg-brand-navy/80 border border-brand-primary/40 rounded-xl max-w-xs inline-block">
                          <span className="block text-xs font-bold text-white">Detecting: Chocolate Croissants</span>
                          <span className="block text-[10px] text-brand-primary font-mono">Count: 42 Units | Acc: 98.4%</span>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* Step 2 Mockup: AI Classification */}
                {activeStep === 2 && (
                  <motion.div
                    key="step-2"
                    initial={{ opacity: 0, scale: 0.98 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    className="space-y-4 w-full"
                  >
                    <div className="flex justify-between items-center bg-white/[0.02] border border-white/5 p-3 rounded-xl">
                      <div className="flex items-center gap-2">
                        <BrainCircuit className="w-4 h-4 text-brand-primary" />
                        <span className="text-xs font-semibold text-white/95">PANTAS AI Sorting Engine Node</span>
                      </div>
                      <Sparkles className="w-4 h-4 text-brand-accent h-4" />
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                      <div className="p-3 bg-brand-primary/5 border border-brand-primary/20 rounded-xl">
                        <span className="block text-[8px] font-mono text-brand-primary uppercase">Tier A</span>
                        <span className="block text-xs font-bold text-white mt-1">Consumer Market</span>
                        <span className="block text-[10px] text-[#94A3B8] mt-0.5">Sale at 60% Off</span>
                        <div className="w-full bg-[#1e293b] h-1 rounded-full mt-2 overflow-hidden">
                          <div className="bg-brand-primary h-full w-[85%]" />
                        </div>
                      </div>

                      <div className="p-3 bg-[#F59E0B]/5 border border-[#F59E0B]/20 rounded-xl">
                        <span className="block text-[8px] font-mono text-[#F59E0B] uppercase">Tier B</span>
                        <span className="block text-xs font-bold text-white mt-1">NGO Donation</span>
                        <span className="block text-[10px] text-[#94A3B8] mt-0.5">Route to Local Food Bank</span>
                        <div className="w-full bg-[#1e293b] h-1 rounded-full mt-2 overflow-hidden">
                          <div className="bg-[#F59E0B] h-full w-[45%]" />
                        </div>
                      </div>

                      <div className="p-3 bg-[#10B981]/5 border border-[#10B981]/20 rounded-xl">
                        <span className="block text-[8px] font-mono text-[#10B981] uppercase">Tier C</span>
                        <span className="block text-xs font-bold text-white mt-1">Upcycling feed</span>
                        <span className="block text-[10px] text-[#94A3B8] mt-0.5">Wet compost Maggot farms</span>
                        <div className="w-full bg-[#1e293b] h-1 rounded-full mt-2 overflow-hidden">
                          <div className="bg-[#10B981] h-full w-[95%]" />
                        </div>
                      </div>

                      <div className="p-3 bg-[#64748B]/5 border border-[#64748B]/20 rounded-xl text-opacity-50">
                        <span className="block text-[8px] font-mono text-[#64748B] uppercase">Tier D</span>
                        <span className="block text-xs font-bold text-white mt-1">Compost</span>
                        <span className="block text-[10px] text-[#475569] mt-0.5">No direct human yield</span>
                        <div className="w-full bg-[#1e293b] h-1 rounded-full mt-2 overflow-hidden">
                          <div className="bg-[#64748B] h-full w-[20%]" />
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* Step 3 Mockup: Smart Distribution */}
                {activeStep === 3 && (
                  <motion.div
                    key="step-3"
                    initial={{ opacity: 0, scale: 0.98 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    className="space-y-4 w-full"
                  >
                    <div className="flex justify-between items-center bg-white/[0.02] border border-white/5 p-3 rounded-xl">
                      <div className="flex items-center gap-1.5">
                        <Navigation className="w-4 h-4 text-brand-primary" />
                        <span className="text-xs font-semibold text-white/95">Smart Routing Active</span>
                      </div>
                      <span className="text-[10px] font-mono text-brand-primary uppercase">Regional District</span>
                    </div>

                    <div className="p-4 bg-[#070A11] border border-white/5 rounded-2xl flex items-center justify-between">
                      <div className="flex items-start gap-3">
                        <MapPin className="w-5 h-5 text-brand-primary shrink-0 mt-0.5" />
                        <div>
                          <span className="block text-xs font-bold text-white">Route ID: PT-9402</span>
                          <p className="text-[10px] text-[#94A3B8] mt-0.5 leading-relaxed">
                            Pickup: Sunan Premier Hotel <br />
                            Destination: Eco Bioconversion Facility
                          </p>
                        </div>
                      </div>
                      <div className="text-right">
                        <span className="block text-xs font-bold text-brand-primary">$0 Free Base</span>
                        <span className="block text-[9px] text-[#64748B] font-mono uppercase mt-0.5">CO₂ Offset +7.2kg</span>
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* Step 4 Mockup: impact and ESG tracking */}
                {activeStep === 4 && (
                  <motion.div
                    key="step-4"
                    initial={{ opacity: 0, scale: 0.98 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.98 }}
                    className="space-y-4 w-full"
                  >
                    <div className="flex justify-between items-center bg-white/[0.02] border border-white/5 p-3 rounded-xl">
                      <div className="flex items-center gap-1.5">
                        <FileCheck className="w-4 h-4 text-brand-emerald" />
                        <span className="text-xs font-semibold text-white/95">GRI 100 Compliant Certificate</span>
                      </div>
                      <Download className="w-4 h-4 text-brand-primary cursor-pointer hover:scale-110 transition-transform" />
                    </div>

                    <div className="p-5 border border-brand-emerald/20 bg-brand-emerald/5 rounded-2xl relative overflow-hidden text-center">
                      <div className="absolute top-2 right-2 border border-brand-emerald/40 text-[8px] font-mono text-brand-emerald bg-brand-navy px-1.5 py-0.5 rounded uppercase font-semibold">
                        AUDITED CORE LEDGER
                      </div>
                      
                      <span className="block text-[11px] font-mono text-[#5f6874] uppercase">ESTABLISHMENT CSR AUDIT CERTIFICATE</span>
                      <h4 className="text-lg font-display font-extrabold text-white mt-1">Sunan Premier Hotel</h4>
                      
                      <div className="grid grid-cols-2 gap-2 mt-4 text-left">
                        <div className="p-2 bg-brand-navy rounded-xl border border-white/5">
                          <span className="block text-[8px] font-mono text-[#64748B]">SAVED MEALS</span>
                          <span className="block text-xs font-mono font-bold text-brand-primary">12,482 (2.4 Tons)</span>
                        </div>
                        <div className="p-2 bg-brand-navy rounded-xl border border-white/5 border-l-2 border-l-brand-emerald">
                          <span className="block text-[8px] font-mono text-[#64748B]">CARBON OFFSET CREDIT</span>
                          <span className="block text-xs font-mono font-bold text-brand-emerald">4,904.3 Kg CO₂e</span>
                        </div>
                      </div>

                      <span className="block text-[9px] font-mono text-[#475569] mt-3 uppercase tracking-wider">
                        ISO 14001:2015 & GRI Food Waste Disclosures compliant
                      </span>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              <div className="mt-4 pt-4 border-t border-white/5 text-center text-[10px] font-mono text-[#475569] uppercase">
                PANTAS SYSTEM OPERATIONS SIMPLIFIED SCREENSHOT
              </div>
            </div>
          </div>

        </div>

      </div>
    </section>
  );
}
